---
# Configure Galaxy to use a Torque LRMS Back-end

# Install pbs_python
- pip: name=python-pbs virtualenv={{galaxy_install_path}}/.venv

# Configure job_conf.xml
- copy:
    content: |
        <?xml version="1.0"?>
        <job_conf>
          <plugins>
            <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="1"/>
            <plugin id="pbs" type="runner" load="galaxy.jobs.runners.pbs:PBSJobRunner"/>
          </plugins>
          <handlers>
            <handler id="main" />
          </handlers>
          <destinations default="pbs">
            <destination id="local" runner="local"/>
            <destination id="pbs" runner="pbs" tags="mycluster" />
            <destination id="pbs_longjobs" runner="pbs" tags="mycluster,longjobs">
              <param id="Resource_List">walltime=72:00:00</param>
            </destination>
          </destinations>
          <tools>
            <tool id="upload1" destination="local"/>
          </tools>
        </job_conf>
    dest: "{{galaxy_install_path}}/config/job_conf.xml"

# Set the databse galaxy path to NFS shared dir
- file: path={{galaxy_install_path}}/database/pbs state=directory recurse=yes
